### ISSUE TITLE
grpc / protobuf / pybind11

### ISSUE THREAD

**Issue by CuriousityLi** [songzhen-neu/ecgraph#1]
您好： 
       您用的版本是什么？我在复现过程中出现了版本不对的问题？恳请您告知我相关的版本信息。 谢谢

**Comment by songzhen0210** [comment]
感谢关注我们的工作，版本如下：
-- Using protobuf 3.19.4.0
-- Using gRPC 1.45.0-dev
-- pybind11 v2.6.0 dev

**Comment by CuriousityLi** [comment]
> 

Thanks ^-^
